# Generated by Django 5.2.1 on 2025-05-11 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='featured_artists',
        ),
        migrations.RemoveField(
            model_name='song',
            name='tags',
        ),
    ]
